# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAll',
            fields=[
                ('movieid', models.AutoField(db_column='movieId', primary_key=True, serialize=False)),
                ('moviename', models.CharField(blank=True, db_column='movieName', max_length=255, null=True)),
                ('moviename_en', models.CharField(blank=True, db_column='movieName_en', max_length=255, null=True)),
                ('releasedate', models.DateField(blank=True, db_column='releaseDate', null=True)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('maoyanid', models.IntegerField(blank=True, db_column='maoyanId', null=True)),
                ('cboooid', models.IntegerField(blank=True, db_column='cboooId', null=True)),
                ('doubanmovieid', models.IntegerField(blank=True, db_column='doubanMovieId', null=True)),
                ('mtimeid', models.IntegerField(blank=True, db_column='mtimeId', null=True)),
                ('taobaoid', models.IntegerField(blank=True, db_column='taobaoId', null=True)),
                ('wepiaoid', models.IntegerField(blank=True, db_column='wepiaoId', null=True)),
                ('weiboid', models.BigIntegerField(blank=True, db_column='weiboId', null=True)),
                ('franchiseid', models.IntegerField(blank=True, db_column='franchiseId', null=True)),
                ('imdbid', models.CharField(blank=True, db_column='imdbId', max_length=500, null=True)),
                ('boxofficemojoid', models.CharField(blank=True, db_column='boxofficemojoId', max_length=500, null=True)),
                ('thenumbersid', models.CharField(blank=True, db_column='theNumbersId', max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'match_all',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieCompany',
            fields=[
                ('movieid', models.IntegerField(blank=True, db_column='movieId', null=True)),
                ('cboooid', models.IntegerField(blank=True, db_column='cboooId', null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('companyid', models.IntegerField(blank=True, db_column='companyId', null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieDaily',
            fields=[
                ('movieid', models.IntegerField(blank=True, db_column='movieId', null=True)),
                ('maoyanid', models.IntegerField(blank=True, db_column='maoyanId', null=True)),
                ('showdate', models.DateField(blank=True, db_column='showDate', null=True)),
                ('sumboxoffice', models.FloatField(blank=True, db_column='sumBoxoffice', null=True)),
                ('dailyboxoffice', models.FloatField(blank=True, db_column='dailyBoxoffice', null=True)),
                ('totalshow', models.FloatField(blank=True, db_column='totalShow', null=True)),
                ('totalviewer', models.FloatField(blank=True, db_column='totalViewer', null=True)),
                ('attendrate', models.FloatField(blank=True, db_column='attendRate', null=True)),
                ('avgpeople', models.FloatField(blank=True, db_column='avgPeople', null=True)),
                ('avgprice', models.FloatField(blank=True, db_column='avgPrice', null=True)),
                ('boxrate', models.FloatField(blank=True, db_column='boxRate', null=True)),
                ('seatrate', models.FloatField(blank=True, db_column='seatRate', null=True)),
                ('showrate', models.FloatField(blank=True, db_column='showRate', null=True)),
                ('totalbox', models.FloatField(blank=True, db_column='totalBox', null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_daily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('movieid', models.IntegerField(db_column='movieId', primary_key=True, serialize=False)),
                ('moviename', models.CharField(blank=True, db_column='movieName', max_length=255, null=True)),
                ('releasedate', models.DateField(blank=True, db_column='releaseDate', null=True)),
                ('maoyanid', models.IntegerField(blank=True, db_column='maoyanId', null=True)),
                ('cboooid', models.IntegerField(blank=True, db_column='cboooId', null=True)),
                ('doubanmovieid', models.IntegerField(blank=True, db_column='doubanMovieId', null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('maoyanratingscore', models.FloatField(blank=True, db_column='maoyanRatingScore', null=True)),
                ('maoyanratingnum', models.FloatField(blank=True, db_column='maoyanRatingNum', null=True)),
                ('wishnum_maoyan', models.FloatField(blank=True, db_column='wishNum_maoyan', null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=255, null=True)),
                ('gross', models.FloatField(blank=True, null=True)),
                ('male', models.FloatField(blank=True, null=True)),
                ('female', models.FloatField(blank=True, null=True)),
                ('age_11_15', models.FloatField(blank=True, null=True)),
                ('age_16_20', models.FloatField(blank=True, null=True)),
                ('age_21_25', models.FloatField(blank=True, null=True)),
                ('age_26_30', models.FloatField(blank=True, null=True)),
                ('age_31_35', models.FloatField(blank=True, null=True)),
                ('age_36_40', models.FloatField(blank=True, null=True)),
                ('age_40_50', models.FloatField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoviePeople',
            fields=[
                ('movieid', models.IntegerField(blank=True, db_column='movieId', null=True)),
                ('cboooid', models.IntegerField(blank=True, db_column='cboooId', null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('peopleid', models.IntegerField(blank=True, db_column='peopleId', null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_people',
                'managed': False,
            },
        ),
    ]
